# Pythonの例外
### 例外とは
例外（exception）とは、プログラムを実行したときに起こるエラーのことです。  
数値を０で割ったり、リストの範囲外を利用したりすると例外になります。  
##### 例外を発生させてみる


```python
print(1 / 0)
```


    ---------------------------------------------------------------------------

    ZeroDivisionError                         Traceback (most recent call last)

    <ipython-input-7-3ec96714f820> in <module>
    ----> 1 print(1 / 0)
    

    ZeroDivisionError: division by zero


##### 例外をキャッチしてみる


```python
try:
    print(1 / 0)
except ZeroDivisionError:   # キャッチする例外クラス名を指定します。
    print('Error')          # 例外クラス名はエラーが起きたときに表示されています。
```

    Error



```python
try:
    print(1 / 0)
except Exception as e:      # 例外の種類がわからない場合は「Exception」を指定します 
    print(e)
```

    division by zero


##### また、「raise」を使って意図的に例外を発生させることができます。


```python
try:
    # 例外を発生
    raise Exception('例外発生','テスト')

except Exception as e:
    print(e.args)
    
```

    ('例外発生', 'テスト')


##### 例外が発生しなかったときの処理を「else」、終了時に常に行う処理を「finally」で記述できます。


```python
def div(a, b):
    try:
        print(a / b)
    except ZeroDivisionError as e:
        print('catch ZeroDivisionError:', e)
    else:
        print('(no error)')
    finally:
        print('finish')

div(10, 2)
print('--------------')
div(10, 0)
```

    5.0
    (no error)
    finish
    --------------
    catch ZeroDivisionError: division by zero
    finish
